from starlette.routing import Route, Router
from ads.views import (
    ads_all,
    ad,
    ad_create,
    ad_edit,
    ad_delete,
    ad_images,
    upload,
    image_edit,
    image_delete,
    edit_upload,
    review_create,
    review_edit,
    review_delete,
    search
)

ads_routes = Router([
    Route("/", endpoint=ads_all,
          methods=["GET", "POST"], name="ads_all"),
    Route("/create", endpoint=ad_create,
          methods=["GET", "POST"], name="ad_create"),
    Route("/edit/{id:int}", endpoint=ad_edit,
          methods=["GET", "POST"], name="ad_edit"),
    Route("/delete/{id:int}", endpoint=ad_delete,
          methods=["GET", "POST"], name="ad_delete"),
    Route("/image-edit/{id:int}", endpoint=image_edit,
          methods=["GET", "POST"], name="image_edit"),
    Route("/image-delete/{id:int}", endpoint=image_delete,
          methods=["POST"], name="image_delete"),
    Route("/edit-upload/{aid:int}", endpoint=edit_upload,
          methods=["POST"], name="edit_upload"),
    Route("/images", endpoint=ad_images,
          methods=["GET", "POST"], name="ad_images"),
    Route("/upload", endpoint=upload,
          methods=["POST"], name="upload"),
    Route("/{id:int}/{slug:str}", endpoint=ad,
          methods=["GET", "POST"], name="ad"),
    Route("/review-create", endpoint=review_create,
          methods=["GET", "POST"], name="review_create"),
    Route("/review-edit/{id:int}", endpoint=review_edit,
          methods=["GET", "POST"], name="review_edit"),
    Route("/review-delete/{id:int}", endpoint=review_delete,
          methods=["GET", "POST"], name="review_delete"),
    Route("/search", endpoint=search, methods=["GET"], name="search"),
])
